modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT License"
issueTrackerURL = "https://github.com/SteveKunG/Indicatia/issues"

[[mods]]
modId = "indicatia"
version = "${version}"
displayName = "Indicatia"
description = "Simple in-game info and small utilities!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/indicatia"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/indicatia_version.json"
logoFile = "logo.png"
authors = "SteveKunG"

[[dependencies.indicatia]]
modId = "forge"
mandatory = true
versionRange = "[37.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "architectury"
mandatory = true
versionRange = "[2.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "stevekungs_lib"
mandatory = true
versionRange = "[5.0.0,)"
ordering = "NONE"
side = "CLIENT"